### PR TITLE
Upgrade to log4net 2.0.15, and cleanup unnecessary code.

### PR DESCRIPTION
**Pull request by josiasgr**
Hello Joel, this is a small cleanup to make this package compatible with the latest log4net.

### CODE REVIEW

**Comment by joelweiss** [comment]
@josiasgr Thanks

**Comment by marcin-krystianc** [comment]
Hi @joelweiss, do you have plans to release a new NuGet package anytime soon? We are very keen on seeing a new release as it would unblock the upgrade of log4net for us.

**Comment by joelweiss** [comment]
Done [Nuget](https://www.nuget.org/packages/Log4net.Appender.Serilog/2.0.0)

**Comment by josiasgr** [comment]
great! thanks Joel.

**Pull request merged**
